`timescale 1ns/1ps

module cache_core_mesi_singleline #(
    parameter int MEM_WORDS = 64
)(
    input  logic clk,
    input  logic rst_n,

    //==============================
    // AXI SIDE REQUEST INTERFACE
    //==============================
    input  logic        axi_rd_req,
    input  logic [31:0] axi_rd_addr,
    output logic        axi_rd_ack,
    output logic [31:0] axi_rd_data,

    input  logic        axi_wr_req,
    input  logic [31:0] axi_wr_addr,
    input  logic [31:0] axi_wr_data,
    output logic        axi_wr_ack,

    //==============================
    // ACE SIDE REQUEST INTERFACE
    //==============================
    input  logic        sn_req,
    input  logic [31:0] sn_addr,
    input  logic [2:0]  sn_snoop,      // 0=ReadShared, 1=ReadUnique, 2=CleanInvalid
    output logic        sn_ack,

    // response info for ace module
    output logic [4:0]  sn_crresp,
    output logic        sn_need_cd,
    output logic        sn_inv_after_cd,

    // CD streaming control
    input  logic        sn_cd_next,     // pulse from ace module when a CD beat is accepted
    output logic [31:0] sn_cd_data,
    output logic        sn_cd_last
);

    //==============================
    // MESI states
    //==============================
    localparam logic [1:0] ST_I = 2'd0;
    localparam logic [1:0] ST_S = 2'd1;
    localparam logic [1:0] ST_E = 2'd2;
    localparam logic [1:0] ST_M = 2'd3;

    //==============================
    // Single cache line (16 bytes)
    //==============================
    logic [27:0] tag_line;         // addr[31:4]
    logic [1:0]  state_line;
    logic [31:0] line_data [0:3];

    //==============================
    // Memory
    //==============================
    logic [31:0] mem [0:MEM_WORDS-1];

    //==============================
    // CD pointer
    //==============================
    logic [1:0] cd_ptr;

    //==============================
    // address helpers (no functions)
    //==============================
    logic [1:0]  rd_word, wr_word;
    logic [27:0] rd_tag,  wr_tag,  sn_tag;
    logic [5:0]  rd_midx, wr_midx;

    logic [31:0] rd_base, wr_base, sn_base;

    assign rd_word = axi_rd_addr[3:2];
    assign wr_word = axi_wr_addr[3:2];

    assign rd_tag  = axi_rd_addr[31:4];
    assign wr_tag  = axi_wr_addr[31:4];
    assign sn_tag  = sn_addr[31:4];

    assign rd_midx = axi_rd_addr[7:2];
    assign wr_midx = axi_wr_addr[7:2];

    assign rd_base = {axi_rd_addr[31:4], 4'b0000};
    assign wr_base = {axi_wr_addr[31:4], 4'b0000};
    assign sn_base = {sn_addr[31:4],     4'b0000};

    //==============================
    // writeback task (Vivado safe)
    //==============================
    task automatic do_writeback(input logic [31:0] base);
        logic [31:0] a0,a1,a2,a3;
        logic [5:0]  m0,m1,m2,m3;
        begin
            a0 = base + 32'd0;
            a1 = base + 32'd4;
            a2 = base + 32'd8;
            a3 = base + 32'd12;

            m0 = a0[7:2];
            m1 = a1[7:2];
            m2 = a2[7:2];
            m3 = a3[7:2];

            mem[m0] = line_data[0];
            mem[m1] = line_data[1];
            mem[m2] = line_data[2];
            mem[m3] = line_data[3];
        end
    endtask

    //==============================
    // fill task (Vivado safe)
    //==============================
    task automatic do_fill(input logic [31:0] base);
        logic [31:0] a0,a1,a2,a3;
        logic [5:0]  m0,m1,m2,m3;
        begin
            a0 = base + 32'd0;
            a1 = base + 32'd4;
            a2 = base + 32'd8;
            a3 = base + 32'd12;

            m0 = a0[7:2];
            m1 = a1[7:2];
            m2 = a2[7:2];
            m3 = a3[7:2];

            line_data[0] = mem[m0];
            line_data[1] = mem[m1];
            line_data[2] = mem[m2];
            line_data[3] = mem[m3];
        end
    endtask

    //==============================
    // COMBINATIONAL OUTPUTS
    //==============================
    // These must NOT be driven from always_ff.
    // All 1-cycle pulses are generated by regs below.
    //==============================

    // registered pulse signals
    logic axi_rd_ack_r, axi_wr_ack_r, sn_ack_r;

    // registered response signals (stable until next snoop)
    logic [4:0] sn_crresp_r;
    logic sn_need_cd_r;
    logic sn_inv_after_cd_r;

    assign axi_rd_ack = axi_rd_ack_r;
    assign axi_wr_ack = axi_wr_ack_r;
    assign sn_ack     = sn_ack_r;

    assign sn_crresp        = sn_crresp_r;
    assign sn_need_cd       = sn_need_cd_r;
    assign sn_inv_after_cd  = sn_inv_after_cd_r;

    // CD streaming is purely combinational from cache line + pointer
    assign sn_cd_data = line_data[cd_ptr];
    assign sn_cd_last = (cd_ptr == 2'd3);

    //==============================
    // reset/init + main sequential
    //==============================
    integer i;
    always_ff @(posedge clk) begin
        if (!rst_n) begin
            tag_line   <= '0;
            state_line <= ST_I;
            cd_ptr     <= 2'd0;

            for (i=0; i<4; i++) line_data[i] <= '0;
            for (i=0; i<MEM_WORDS; i++) mem[i] <= '0;

            axi_rd_data <= 32'h0;

            axi_rd_ack_r <= 1'b0;
            axi_wr_ack_r <= 1'b0;
            sn_ack_r     <= 1'b0;

            sn_crresp_r       <= 5'b10000;
            sn_need_cd_r      <= 1'b0;
            sn_inv_after_cd_r <= 1'b0;

        end else begin

            // default pulse outputs (1-cycle)
            axi_rd_ack_r <= 1'b0;
            axi_wr_ack_r <= 1'b0;
            sn_ack_r     <= 1'b0;

            // CD pointer increment when a CD beat is accepted
            if (sn_cd_next) begin
                if (cd_ptr == 2'd3) cd_ptr <= 2'd0;
                else                cd_ptr <= cd_ptr + 2'd1;
            end

            //==========================
            // Priority: SNOOP > AXI
            //==========================

            //==========================
            // SNOOP REQUEST
            //==========================
            if (sn_req) begin
                sn_ack_r <= 1'b1;
                cd_ptr   <= 2'd0;

                // default response for every snoop
                sn_crresp_r       <= 5'b10000; // OK
                sn_need_cd_r      <= 1'b0;
                sn_inv_after_cd_r <= 1'b0;

                // HIT check
                if ((state_line != ST_I) && (tag_line == sn_tag)) begin

                    unique case (sn_snoop)

                        // ReadShared
                        3'd0: begin
                            if (state_line == ST_M) begin
                                sn_crresp_r[0] <= 1'b1; // DataTransfer
                                sn_crresp_r[1] <= 1'b1; // IsShared
                                sn_crresp_r[2] <= 1'b1; // WasDirty
                                sn_need_cd_r   <= 1'b1;

                                do_writeback(sn_base);
                                state_line <= ST_S;
                            end
                            else if (state_line == ST_E) begin
                                sn_crresp_r[1] <= 1'b1; // IsShared
                                state_line <= ST_S;
                            end
                            else if (state_line == ST_S) begin
                                sn_crresp_r[1] <= 1'b1; // IsShared
                            end
                        end

                        // ReadUnique
                        3'd1: begin
                            if (state_line == ST_M) begin
                                sn_crresp_r[0] <= 1'b1; // DataTransfer
                                sn_crresp_r[2] <= 1'b1; // WasDirty
                                sn_need_cd_r   <= 1'b1;
                                sn_inv_after_cd_r <= 1'b1;

                                do_writeback(sn_base);
                                // invalidate after CD done (ace module will stream 4 beats)
                            end
                            else begin
                                state_line <= ST_I;
                            end
                        end

                        // CleanInvalid
                        3'd2: begin
                            if (state_line == ST_M) begin
                                sn_crresp_r[2] <= 1'b1; // WasDirty
                                do_writeback(sn_base);
                            end
                            state_line <= ST_I;
                        end

                        default: begin end
                    endcase
                end
            end

            //==========================
            // AXI WRITE REQUEST
            //==========================
            else if (axi_wr_req) begin
                axi_wr_ack_r <= 1'b1;

                // HIT?
                if ((state_line != ST_I) && (tag_line == wr_tag)) begin
                    line_data[wr_word] <= axi_wr_data;
                    mem[wr_midx] <= axi_wr_data; // write-through
                    state_line <= ST_M;
                end
                else begin
                    // evict if M
                    if (state_line == ST_M) begin
                        do_writeback(wr_base);
                    end

                    // allocate
                    tag_line <= wr_tag;
                    do_fill(wr_base);

                    // write new data
                    line_data[wr_word] <= axi_wr_data;
                    mem[wr_midx] <= axi_wr_data;
                    state_line <= ST_M;
                end
            end

            //==========================
            // AXI READ REQUEST
            //==========================
            else if (axi_rd_req) begin
                axi_rd_ack_r <= 1'b1;

                // HIT?
                if ((state_line != ST_I) && (tag_line == rd_tag)) begin
                    axi_rd_data <= line_data[rd_word];
                end
                else begin
                    // writeback if M
                    if (state_line == ST_M) begin
                        do_writeback(rd_base);
                    end

                    // allocate
                    tag_line <= rd_tag;
                    do_fill(rd_base);

                    // single-cache assumption => Exclusive
                    state_line <= ST_E;

                    axi_rd_data <= mem[rd_midx];
                end
            end

            //==========================
            // Invalidate after CD streaming is done
            //==========================
            // This is needed for ReadUnique when M:
            // after the last CD beat is accepted, invalidate the line.
            if (sn_cd_next && sn_cd_last && sn_inv_after_cd_r) begin
                state_line <= ST_I;
                sn_inv_after_cd_r <= 1'b0; // clear
            end

        end
    end

endmodule
